# Generated by Django 5.1.7 on 2025-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_userpreference_options_userpreference_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityhistory',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
