# Generated by Django 5.0.2 on 2025-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_intensity',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('GYM', 'Gym'), ('SWIMMING', 'Swimming'), ('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('YOGA', 'Yoga'), ('BASKETBALL', 'Basketball'), ('FOOTBALL', 'Football'), ('TENNIS', 'Tennis'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='indoor_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_distance',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum distance in kilometers', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activity_types',
            field=models.CharField(help_text='Comma-separated list of activity types', max_length=100),
        ),
    ]
