# Generated by Django 5.1.7 on 2025-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_userpreference_preferred_intensity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['user__username'], 'verbose_name_plural': 'User preferences'},
        ),
        migrations.AddField(
            model_name='userpreference',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
