# Generated by Django 5.0.2 on 2025-04-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activityhistory_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityhistory',
            name='start_time',
        ),
    ]
