# Generated by Django 5.0.2 on 2025-04-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_activityhistory_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('RUNNING', 'Running/Jogging/Walking'), ('SWIMMING', 'Swimming'), ('BADMINTON', 'Badminton'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('TABLE_TENNIS', 'Table Tennis'), ('VOLLEYBALL', 'Volleyball'), ('PICKLEBALL', 'Pickleball'), ('GYM', 'Gym'), ('FOOTBALL', 'Soccer/Football'), ('SQUASH', 'Squash'), ('NETBALL', 'Netball'), ('LAWN_BOWL', 'Lawn Bowl'), ('HOCKEY', 'Hockey'), ('YOGA', 'Yoga')], max_length=20),
        ),
    ]
