# Generated by Django 5.0.2 on 2025-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_userpreference_preferred_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='indoor_preference',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Maximum distance in kilometers', max_digits=5),
        ),
    ]
