# Generated by Django 5.2 on 2025-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_userpreference_indoor_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('GYM', 'Gym'), ('SWIMMING', 'Swimming'), ('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('YOGA', 'Yoga'), ('BASKETBALL', 'Basketball'), ('FOOTBALL', 'Football'), ('TENNIS', 'Tennis'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='indoor_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='max_distance',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum distance in kilometers', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activity_types',
            field=models.CharField(help_text='Comma-separated list of activity types', max_length=100),
        ),
    ]
