# Generated by Django 5.2 on 2025-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('GYM', 'Gym'), ('SWIMMING', 'Swimming'), ('RUNNING', 'Running'), ('BASKETBALL', 'Basketball'), ('FOOTBALL', 'Football'), ('TENNIS', 'Tennis'), ('BADMINTON', 'Badminton'), ('TABLE_TENNIS', 'Table Tennis'), ('VOLLEYBALL', 'Volleyball'), ('SQUASH', 'Squash'), ('HOCKEY', 'Hockey'), ('PICKLEBALL', 'Pickleball'), ('NETBALL', 'Netball'), ('LAWN_BOWL', 'Lawn Bowl'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
