# Generated by Django 5.2 on 2025-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activity_types',
            field=models.CharField(blank=True, help_text='Comma-separated list of activity types', max_length=200),
        ),
    ]
