# Generated by Django 5.2 on 2025-04-08 14:33

from django.db import migrations

def fix_activity_types(apps, schema_editor):
    UserPreference = apps.get_model('activities', 'UserPreference')
    
    # Activity type mapping (from character sequence to proper name)
    activity_mappings = {
        'S,W,I,M,M,I,N,G': 'swimming',
        'B,A,D,M,I,N,T,O,N': 'badminton',
        'B,A,S,K,E,T,B,A,L,L': 'basketball',
        'T,E,N,N,I,S': 'tennis',
        'V,O,L,L,E,Y,B,A,L,L': 'volleyball',
        'S,O,C,C,E,R': 'soccer',
        'R,U,N,N,I,N,G': 'running'
    }
    
    for pref in UserPreference.objects.all():
        if pref.preferred_activity_types:
            # Remove any spaces and get the raw string
            raw_types = ''.join(pref.preferred_activity_types.split())
            
            # Try to match with known patterns
            matched_activities = []
            for pattern, activity in activity_mappings.items():
                if pattern in raw_types:
                    matched_activities.append(activity)
            
            # Update the preference with proper format
            if matched_activities:
                pref.preferred_activity_types = ','.join(matched_activities)
                pref.save()

def reverse_activity_types(apps, schema_editor):
    # We can't reliably reverse this operation
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0012_alter_userpreference_preferred_activity_types'),
    ]

    operations = [
        migrations.RunPython(fix_activity_types, reverse_activity_types),
    ]
