# Generated by Django 5.2 on 2025-04-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_add_activity_images'),
        ('activities', '0013_fix_activity_types'),
    ]

    operations = [
    ]
